name: chat_rocket_flutter

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  dart_meteor_web: ^1.1.2
  just_audio: ^0.5.5
  link: ^1.1.0
  microphone: ^0.0.2+3
  file_picker_web: ^1.0.2+1
  stop_watch_timer: ^0.6.0+1
  positioned_tap_detector: ^1.0.3
  material_design_icons_flutter: ^4.0.5755
  badges: ^1.1.3
  cached_network_image: ^2.3.3
  photo_view: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true