name: chat_rocket_flutter
publish_to: none

version: 0.2.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  dart_meteor: ^2.0.4
  link: ^1.1.0
  microphone: ^0.1.0
  positioned_tap_detector: ^1.0.3
  material_design_icons_flutter: ^5.0.6295
  badges: ^2.0.1
  photo_view: ^0.13.0
  just_audio: ^0.9.13
  stop_watch_timer: ^1.3.1
  cached_network_image: ^3.1.0
  file_picker: ^4.1.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true