name: chat_rocket_flutter

version: 0.1.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  dart_meteor_web: ^1.1.2
  link: ^1.1.0
  microphone: ^0.1.0
  file_picker_web: ^2.0.0
  positioned_tap_detector: ^1.0.3
  material_design_icons_flutter: ^4.0.5955
  badges: ^2.0.1
  photo_view: ^0.13.0
  just_audio: ^0.6.15+1
  stop_watch_timer: ^0.6.0+1
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true